# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://jzl0257.github.io/she/"

git_url = "https://github.com/jzl0257/she/tree/master/"

def custom_doc_links(name): return None
